import torch


def triad(a: torch.Tensor, b: torch.Tensor, scalar: float) -> torch.Tensor:
    """Compute c = a + scalar * b for CUDA tensors already on the GPU.

    To maximize achieved bandwidth (GB/s), we must minimize total DRAM traffic. 
    The naive `a + scalar * b` performs two memory passes:
    1. Read 'b', compute product, write intermediate tensor T to VRAM.
    2. Read 'a' and 'T', sum them, write result 'c' back to VRAM.

    Total traffic for size N (float32): 4 * N bytes read + 4 * N written per pass = 8N reads/writes total? No:
    Pass 1: Load b(4B), Store T(4B) -> 8B/element.
    Pass 2: Load a(4B), Load T(4B), Store c(4B) -> 12B/element. Total = 20 bytes per element? No, that's wrong math for STREAM metrics (which usually track Reads + Writes).

    A fused kernel performs exactly one pass:
    Load a and b, compute result in registers, write c back once.
    Traffic pattern of Fused Kernel: Read 'a'(4B) + Read 'b'(4/8 B), Write 'c' (4B). 
    Total traffic = sum(size_of_inputs * reads + size_of_outputs * writes).

    Using `torch.compile` with the default Inductor backend triggers Triton kernel fusion,
    which implements this single-pass pattern automatically and is highly optimized for CUDA architectures.
    """
    # We use a compiled version of the logic to ensure one pass over memory (Kernel Fusion)
    # This eliminates intermediate allocations and reduces DRAM traffic from ~20B/elem or 16B/elem down towards 12B/elem minimums.
    @torch.compile(mode="max-autotune")
    def fused_triad(a: torch.Tensor, b: torch.Tensor, s: float) -> torch.Tensor:
        # In a single Triton kernel generated by inductor, this is one load of A and B 
        # followed by one store to C.
        return torch.add(a, b * s)

    return fused_triad(a, b, scalar)


